### PR TITLE
ANDAUTH-88 fixed UI issue in Signin Viewflipper

### PR DESCRIPTION
**Pull request by somenath1435**
The login button is now properly visible. For the issue, check jira.

### CODE REVIEW

**Comment by InsanusMokrassar** [comment]
Can you, please, send here screenshot like in an issue?

**Comment by somenath1435** [comment]
@InsanusMokrassar 
Before:
Screenshot_20200529-163444

After:
Screenshot_20200621-050423

**Review by InsanusMokrassar — APPROVED** [review]

**Comment by InsanusMokrassar** [comment]
@somenath1435 I have updated UI. Please, check it and update screenshots Before/After (I can't do this due to limitations of my hardware :disappointed: )

**Comment by somenath1435** [comment]
@InsanusMokrassar There is a problem, the error message "invalid credentials" is coming but not properly visible(less than 10% visible) and I need to scroll (scrollview working) to see it

**Comment by InsanusMokrassar** [comment]
@somenath1435 fixed

**Pull request merged**
