### PR TITLE
ANDAUTH-96 Notification REST API integration

### PR DESCRIPTION
**Pull request by somenath1435**
Integration of Notification REST API with android notifications.

Feature 1: Display All notifications in NotificationActivity.
Feature 2: Show the notifications as android notifications and keep checking for new notifications every 15 mins.

Clicking on each notification should redirect to the relevant page.

### CODE REVIEW

**Comment by somenath1435** [comment]
@InsanusMokrassar @tmortagne This PR contains too many errors since I'm exploring a lot.

**Comment by somenath1435** [comment]
@InsanusMokrassar Look at the following files:
XwikiServices (line 162 onwards) for apis(tried many ways)
SingInViewFlipper (line 256) : Working correctly(status 200 and correct log output)
SyncSettingsActivity(line 789): HTTP error 400(bad request) and 401(unauthorised , when basic auth not done)
NotificationsActivity(line 58): HTTP error 400(bad request) and 401(unauthorised , when basic auth not done)

Other things commented out : 
Tried Work Manager to display notifications with period of  15 mins.
Added bell icon in toolbar of SyncSettingsActivity to launch NotificationsActivity.

Main Problem: XwikiServices.getNotify() not working as expected in most calls.
Also, struggling to get username and password in files except SignInViewFlipper

Note: There are lot of hardcoded stuffs which will be refactored later.(Especially in XwikiSerivices)
Note: Credentails given in code(The password, while performing Credentials.Basic(name,password) ) is wrong(intentional). No need to worry about it.

**Comment by somenath1435** [comment]
@InsanusMokrassar PR is updated, please pull and see if there are any errors.
Click bell icon to see if your is being displayed.
Work Manager is configured which will check for xwiki notification every 15 mins and display android notifications accordingly

**Comment by somenath1435** [comment]
@InsanusMokrassar 
The following things need to be checked:
Clicking on the bell icon is displaying all notifications for the user(if no notification is available, then "no notification found" message should be displayed), and clicking on the notification should open NotificationsActivity for now.
Every 15 mins, android notifications should be displayed to show the notifications.
Android notifications are working for Android 9 and 8. Need to test for older versions(especially V5).

Note: I'm only displaying the document and type of notifications(can be changed later as per discussions)
Onclick functionality of each notification must be discussed soon.

**Comment by somenath1435** [comment]
@InsanusMokrassar @tmortagne 
The new-look:
For a particular user ("rest/notifications?userId=*****") :
This will be present in final version.


For all users  (rest/notifications) :
This is for testing only.

**Comment by somenath1435** [comment]
@InsanusMokrassar 
The following things should be noted:

1. I'm using random() to generate random ids for each notifications(Will be changed soon, maybe after evaluation)

2. I've hardcoded the server address to generate the link for page API call. It is of format: {server}/wikis/{wikiname}/spaces/{spacename}/pages/{pagename}

See line 89 of NotificationsAdapter and line 94 of NotificationsWorker.
Please try to use custom server address input in AuthenticatorActivity (I could not do it).

**Comment by somenath1435** [comment]
@InsanusMokrassar Please refactor the PR as you want. I have implemented all the requirements mostly.

**Comment by somenath1435** [comment]
@InsanusMokrassar PR is updated. Now Notifications api is being called using async. Also, Page title is being shown in android notifications.

**Comment by somenath1435** [comment]
The api call with asyncid will return asyncid or the notifications(not both) . I used if else checks and do-while loop for that purpose.

**Comment by somenath1435** [comment]
New-Look:

**Comment by tmortagne** [comment]
The `&amp;` in the screenshot looks like a bug, was it fixed since ?

**Pull request merged**
