### PR TITLE
ANDAUTH-65 use chrome tabs to display learn more page

### PR DESCRIPTION
**Pull request by somenath1435**
Chrome Tabs are faster than default browser view.

A lot of customizations can be done within the app itself.

ezgif com-video-to-gif

### CODE REVIEW

**Comment by somenath1435** [comment]
@InsanusMokrassar please review this

**Comment by InsanusMokrassar** [comment]
I am not sure that we need to do this like it. I mean, adding of new dependency and using of this look like shooting the sparrows with a cannon. Anyway, you can keep it in mind for future for case when (and if) we will need some big features in webview (comment is just a copy from [jira](https://jira.xwiki.org/browse/ANDAUTH-66?focusedCommentId=104938&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-104938))

**Comment by tmortagne** [comment]
I agree with @InsanusMokrassar regarding the useless dependency and I'm actually wondering if it would not make more sense to simply open whatever is the default browser instead of an integrated view. This is just a link to the website and not really an application feature.

**Comment by somenath1435** [comment]
@InsanusMokrassar @tmortagne what shall I do?

**Comment by InsanusMokrassar** [comment]
> @InsanusMokrassar @tmortagne what shall I do?

If you are thinking that we still must merge it - just say us your view point and lets discuss. Otherwise, we will close this PR. I think so

**Comment by somenath1435** [comment]
@InsanusMokrassar please read this https://droidmentor.com/chrome_custom_tabs

**Comment by InsanusMokrassar** [comment]
Closed due to closing of source issue https://jira.xwiki.org/projects/ANDAUTH/issues/ANDAUTH-66

**Pull request closed without merging**
