### PR TITLE
ANDAUTH-80 replace deprecated function

### PR DESCRIPTION
**Pull request by somenath1435**
isAvailable() function to check internet connectivity is currently deprecated and should be replaced by isConnected() function

### CODE REVIEW

**Comment by somenath1435** [comment]
@InsanusMokrassar please review this one too

**Comment by somenath1435** [comment]
@InsanusMokrassar @tmortagne how can I communicate with you(except IRC)? I want to discuss about gsoc proposal. Can you provide any communication channels like email/hangouts/Whatsapp/Facebook etc

**Comment by tmortagne** [comment]
@somenath1435 you should use [the Matrix/Riot chat](https://dev.xwiki.org/xwiki/bin/view/Community/Chat#HRiot.im) for short communication, that's how short things are discussed in XWiki. For longer discussions and proposals you should use [the forum](https://dev.xwiki.org/xwiki/bin/view/Community/Discuss#HForum).

**Comment by InsanusMokrassar** [comment]
@somenath1435 we are both available in the group in Riot.im . As I understand, I can add you if you provide your riot id

**Review by InsanusMokrassar — APPROVED** [review]

**Review by tmortagne — APPROVED** [review]

**Comment by somenath1435** [comment]
@InsanusMokrassar what is your riot/matrix id?? Mine is somenath

**Comment by InsanusMokrassar** [comment]
Unfortunately, the whole [NetworkInfo](https://developer.android.com/reference/android/net/NetworkInfo) is deprecated

**Comment by InsanusMokrassar** [comment]
I will think what to do with this deprecation and with this PR

**Comment by InsanusMokrassar** [comment]
Closed due to absent of fixes and potential improvement

**Pull request closed without merging**
